### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pysailor** [wichert/htmllaundry#6]
Hi @wichert,
with some recent changes merged in, could you please make a new release?

I realize in #5 I forgot to add a change note. I would write:
When removing empty tags, allow to define additional tags that are considered OK to be empty

**Comment by wichert** [comment]
Since I’m too busy  right now I have given you commit access to the repo and owner access on PyPI. Can you create the new release?

**Comment by pysailor** [comment]
Thank you! Will do

**Comment by pysailor** [comment]
Done
